name: TerriblePlugin
version: @version@
main: dev.jaims.terribleplugin.Main
depend:
  - GroupManager
permissions:
  terribleplugin.permission:
    default: true
commands:
  command:
    permission: terribleplugin.permission
  hello:
    description: hello
  heal:
    permission: terribleplugin.heal
    description: turns a player to healthy mode
